services:
    frontend:
        build:
            context: .
            dockerfile: .config/dev.Dockerfile
        env_file:
            - ./.env
        container_name: vatsim-radar
        expose:
            - 8080
            - 9229
        command: /radar/.config/command.sh
        ports:
            - "8080:8080"
            - "8880:8880"
        volumes:
            - ".:/radar:rw"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mysql
        cap_add:
            - SYS_NICE
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=radar
            - MYSQL_ROOT_PASSWORD=localhost
        ports:
            - '3306:3306'
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 5s
            interval: 5s
            retries: 40
        volumes:
            - .config/db:/var/lib/mysql
